#!/bin/bash

#SBATCH --job-name=llama2-maxtext-train
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --partition=g2gpu8multinode
#SBATCH --output=output.txt
#SBATCH --error=err.txt
#SBATCH --time=01:00:00
nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

srun bash /data_bucket/train.sh $head_node_ip